### ISSUE TITLE
PR, possibly?

### ISSUE THREAD

**Issue by tmcw** [tomekmarchi/docredux#5]
Hi Thomas,

Tom (documentation.js) here. Great to see that you're interested in enhancing documentation.js - any chance those enhancements can take the form of a PR so that we don't have to fork & maintain two codebases?

**Comment by tomekmarchi** [comment]
@tmcw The entire project will most likely be re-written. For now it's going through the internals and bringing all the ecmascript up to date. Will take a while but even at this point my local changes would be a nightmare to merge. Many files have already been gutted the eslint config prior was an absolute mess stuck in es5 land. For now this is what I need to render my docs correctly. The template system will change over to a standalone node server using RethinkDB as the backend & Ractive on the front-end. In all honesty the fork will just be moving in a different direction. By the end of it I can't imagine a single file remaining from the original fork. Paying nothing more than homage to the stone giant it once stood upon.

**Comment by tmcw** [comment]
All right then, best of luck! Appreciate the taking it in a different direction, though you might want to avoid calling folks work a mess :)
